apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-test-secret
  namespace: default
spec:
  refreshInterval: 10s # 刷新时间
  secretStoreRefs:
    - name: secret-store-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: test-secret # 要推送的 K8s secret 名称
  data:
    - match:
        secretKey: PASSWORD # 要推送的 K8s Secret key
        remoteRef:
          remoteKey: k8s/test-secret # Vault path
          property: PASSWORD # Vault key
    - match:
        secretKey: USERNAME # 要推送的 K8s Secret key
        remoteRef:
          remoteKey: k8s/test-secret # Vault path
          property: USERNAME # Vault key