apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore #Kubernetes resource type
metadata:
  name: secret-store-vault #resource name
spec:
  provider:
    vault: #specifies vault as the provider
      server: "http://vault.vault.svc.cluster.local:8200" #the address of your vault instance
      version: "v2" #Vault API version
      path: "k8s"
      auth:
        tokenSecretRef:
          name: "vault-token" #Use a secret called vault-token
          key: "token" #Use this key to access the vault token
