apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
data:
  haproxy.cfg: |
    global
    log stdout format raw local0
    maxconn 2000
    user haproxy
    group haproxy
    defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
    frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back
    backend http_back
    balance roundrobin
    option httpchk
    http-check send meth GET uri / ver HTTP/1.1 hdr Host bookinfo.example.local
    http-check expect status 200
    server cluster2 124.156.160.164:80 check weight 80
    server cluster3 43.128.24.229:80 check weight 20