apiVersion: v1
kind: Secret
metadata:
  name: result-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- template "imagePullSecret" (dict "imagePullSecret" .Values.RESULT.IMAGEPULLSECRET) }}