apiVersion: v1
kind: Secret
metadata:
  name: yamltoinfra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/sawyer523/geektime-devops"
  password: "" # your github personal access token
  username: "sawyer523"
  insecure: "true"
  forceHttpBasicAuth: "true"
  enableLfs: "true"