apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: week9-prometheus-app-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: week9-prometheus-app
  endpoints:
    - port: web
      interval: 10s
      path: /metrics